### ISSUE TITLE
GUI tracker

### ISSUE THREAD

**Issue by kyle-gardner** [BryceLucas/GriZilly#11]
Tracker for (probably not) everything we need for the GUI

1. Bottom bar

- [ ] play/pause buttons
- [ ] next/previous buttons
- [ ] progress bar 
- [ ] display the currently playing song + artist

2. Playlist bar

- [ ] show all playlists
- [ ] choose between a ListView or a TableView

3. Song Pane

- [ ] Read songs from the playlist and show all the songs along with their metadata in the pane
- [ ] Play button on the left side like on spotify if we have time
